name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run:  |
          sudo apt --yes purge glib-networking
          sudo apt --yes --purge autoremove
          sudo apt update || true
          sudo apt --yes --no-install-recommends install libglib2.0-dev libbson-dev libleveldb-dev liblmdb-dev libmongoc-dev libsqlite3-dev librados-dev libfuse-dev libmariadb-dev librocksdb-dev
          sudo apt --yes --no-install-recommends install python3 python3-pip python3-setuptools python3-wheel ninja-build
          sudo pip3 install meson
          git clone https://github.com/wr-hamburg/julea.git
          cd julea
          ./scripts/install-dependencies.sh
          . scripts/environment.sh
          meson setup --prefix="${GITHUB_WORKSPACE}/julea-install" -Db_sanitize=address,undefined bld
          ninja -C bld
          julea-config --user \
             --object-servers="$(hostname)" --kv-servers="$(hostname)" --db-servers="$(hostname)" \
            --object-backend=posix --object-component=server --object-path=/tmp/julea/posix \
            --kv-backend=lmdb --kv-component=server --kv-path=/tmp/julea/lmdb \
            --db-backend=sqlite --db-component=server --db-path=/tmp/julea/sqlite
          cd 
          ./autogen.sh
          export PKG_CONFIG_PATH=$JULEA_PREFIX/lib/pkg-config && 
          ./configure --disable-fortan --prefix=${GITHUB_WORKSPACE}/install --with-device=ch3 --with-file-system=ufs+julea
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
